[book]
language = "zh-TW"
src = "src"
title = "NTHU CPP"

[build]
build-dir = "book"
create-missing = false

[output.html]
mathjax-support = true
git-repository-url = "https://github.com/NTHU-CP/NTHU-CPP"
no-section-label = true

[output.html.print]
enable = false

[output.html.fold]
enable = true
